name: Deploy to VDS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VDS to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VDS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VDS
        env:
          VDS_HOST: ${{ secrets.VDS_HOST }}
          VDS_USER: ${{ secrets.VDS_USER }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no $VDS_USER@$VDS_HOST << 'EOF'
            cd $DEPLOY_DIR
            git fetch origin
            git reset --hard origin/main
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF